// GENERATED by scripts/build-contributors.ts from the GitHub contributors API.
// Do not edit; run `npm run build:content` (or `npm run build`) to refresh.

export interface Contributor {
  username: string;
  commits: number;
}

export const contributors: Contributor[] = [
  {
    "username": "gustavlrsn",
    "commits": 159
  }
];
