/**
 * Build-time script: embeds the App Developer Guide and a type digest
 * generated from the same source set the /system/source volume ships.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import ts from "typescript";
import { APP_TITLES, bundledAppsGuideRows } from "../apps/sdkClean";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

export const GUIDE_PATH = path.join(ROOT, "packages", "sdk", "docs", "APP_DEV_GUIDE.md");
export const OUTPUT_PATH = path.join(ROOT, "api", "mockintosh-context.generated.ts");

function extractJsxDigest(): string {
  const jsx = fs.readFileSync(path.join(ROOT, "packages/ui/src/jsx.d.ts"), "utf8");
  const nodes = fs.readFileSync(path.join(ROOT, "packages/ui/src/nodes.ts"), "utf8");
  const names = ["BoxProps", "TextProps", "ImageProps", "RasterProps", "BitmapProps", "RasterSurface", "Ink"];
  const parts = ["JSX intrinsics: box, text, image, raster, bitmap — /system/source/packages/ui/src/jsx.d.ts"];
  for (const name of names) {
    const match = nodes.match(new RegExp(`export (?:interface|type) ${name}[^{]*\\{[^}]*\\}`, "s"));
    if (match) parts.push(`${name} (/system/source/packages/ui/src/nodes.ts):\n${match[0].slice(0, 600)}`);
  }
  parts.push(jsx.includes("bitmap") ? "onDrag / onMouseDown live on BitmapProps in nodes.ts" : "");
  return parts.filter(Boolean).join("\n\n");
}

function extractSdkExports(): string {
  const index = path.join(ROOT, "packages/sdk/src/index.ts");
  const program = ts.createProgram([index], { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext });
  const checker = program.getTypeChecker();
  const source = program.getSourceFile(index);
  if (!source) return "";
  const lines: string[] = ["@mockintosh/sdk exports (/system/source/packages/sdk/src/index.ts):"];
  const symbol = checker.getSymbolAtLocation(source);
  const exports = symbol ? checker.getExportsOfModule(symbol) : [];
  for (const item of exports.slice(0, 80)) {
    const name = item.getName();
    if (name.startsWith("__")) continue;
    lines.push(`- ${name}`);
  }
  lines.push("Sprite, Ink, PatternName, RasterSurface — /system/source/packages/ui/src/nodes.ts and sprite.ts");
  return lines.join("\n");
}

function sourceMap(): string {
  const rows = bundledAppsGuideRows();
  const exemplars = rows
    .filter((row) => row.kind === "SDK-clean")
    .map((row) => {
      const extra =
        row.source === "MacPaint.tsx"
          ? "bitmap engine, tools palette, undo, patterns, sprite files"
          : row.source === "PhotoBooth.tsx"
            ? "camera + scheduler + dither"
            : row.source === "Picture.tsx"
              ? "images.decode + toBits"
              : APP_TITLES[row.source as keyof typeof APP_TITLES] ?? row.title;
      return `- ${row.title} → /system/source/apps/${row.source} (${extra})`;
    });
  return [
    "Read the running OS, not GitHub. Paths are under /system/source.",
    "Model only on SDK-clean apps.",
    "",
    "Where to look:",
    "- pointer events → /system/source/packages/ui/src/pointer.ts",
    "- JSX props → /system/source/packages/ui/src/jsx.d.ts and nodes.ts",
    "- SDK contract → /system/source/packages/sdk/src/index.ts",
    "- architecture → /system/source/ARCHITECTURE.md",
    "- in-OS project mockintosh.json → {id, title, entry: \"src/index.tsx\", sdkVersion: \"3\"} only. author/icon/description/sdk belong to the App Store catalog, not this file. See /system/source/packages/sdk/docs/APP_DEV_GUIDE.md",
    "- save to Desktop → fs.locate(\"desktop\") + writeFile(..., { type: MIME.text }). app.storage is not the Desktop. Photo Booth writes sprites the same way.",
    "",
    "SDK-clean exemplars:",
    ...exemplars,
    "",
    "Recipes: put the pixel engine in src/engine.ts and the view in src/index.tsx; keep an undo stack of pixel buffers; name controls with semantic={{name}} / Button name=; leave room below a bitmap for chrome.",
  ].join("\n");
}

export function renderChatContextModule(guide: string, digest: string, map: string): string {
  return [
    "// GENERATED by scripts/build-chat-context.ts from packages/sdk/docs/APP_DEV_GUIDE.md and shipped sources.",
    "// Do not edit; edit the guide or sources and run `npm run build:content`.",
    "",
    "/** The App Developer Guide, verbatim, for the ChatGippity system prompt. */",
    `export const APP_DEV_GUIDE = ${JSON.stringify(guide)};`,
    "",
    "/** Compact type digest generated from the same sources as /system/source. */",
    `export const TYPE_DIGEST = ${JSON.stringify(digest)};`,
    "",
    "/** Map of the source volume and SDK-clean exemplars. */",
    `export const SOURCE_MAP = ${JSON.stringify(map)};`,
    "",
  ].join("\n");
}

export function buildChatContext(): string {
  return renderChatContextModule(
    fs.readFileSync(GUIDE_PATH, "utf8"),
    `${extractJsxDigest()}\n\n${extractSdkExports()}`,
    sourceMap(),
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  fs.writeFileSync(OUTPUT_PATH, buildChatContext());
  console.log(`✓ ${path.relative(ROOT, OUTPUT_PATH)}`);
}
