/**
 * Build-time script: embeds the App Developer Guide into the ChatGippity
 * system prompt, so the assistant learns the SDK from the same document
 * developers read instead of from a hand-maintained summary that drifts.
 *
 * Writes `api/mockintosh-context.generated.ts`; `api/mockintosh-context.ts`
 * imports it. Runs as part of `build:content`. The generated file is
 * committed so type-checking works on a fresh clone; `chat-context.test.ts`
 * fails when it is stale.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

export const GUIDE_PATH = path.join(ROOT, "packages", "sdk", "docs", "APP_DEV_GUIDE.md");
export const OUTPUT_PATH = path.join(ROOT, "api", "mockintosh-context.generated.ts");

export function renderChatContextModule(guide: string): string {
  return [
    "// GENERATED by scripts/build-chat-context.ts from packages/sdk/docs/APP_DEV_GUIDE.md.",
    "// Do not edit; edit the guide and run `npm run build:content`.",
    "",
    "/** The App Developer Guide, verbatim, for the ChatGippity system prompt. */",
    `export const APP_DEV_GUIDE = ${JSON.stringify(guide)};`,
    "",
  ].join("\n");
}

export function buildChatContext(): string {
  return renderChatContextModule(fs.readFileSync(GUIDE_PATH, "utf8"));
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  fs.writeFileSync(OUTPUT_PATH, buildChatContext());
  console.log(`✓ ${path.relative(ROOT, OUTPUT_PATH)}`);
}
