/**
 * Build-time fetch of GitHub contributors for the Finder About box.
 * Offline / rate-limited builds keep the last generated file.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
export const OUTPUT_PATH = path.join(ROOT, "apps", "finder", "contributors.generated.ts");

export interface Contributor {
  username: string;
  commits: number;
}

const DEFAULT_REPO = { owner: "mockintosh", repo: "mockintosh" };

export function resolveRepo(env: NodeJS.ProcessEnv = process.env): { owner: string; repo: string } {
  const fromGithub = env.GITHUB_REPOSITORY;
  if (fromGithub?.includes("/")) {
    const [owner, repo] = fromGithub.split("/");
    if (owner && repo) return { owner, repo };
  }
  const owner = env.VERCEL_GIT_REPO_OWNER;
  const repo = env.VERCEL_GIT_REPO_SLUG;
  if (owner && repo) return { owner, repo };
  return DEFAULT_REPO;
}

export function parseLinkNext(link: string | null): string | undefined {
  if (!link) return undefined;
  for (const part of link.split(",")) {
    const match = part.match(/<([^>]+)>\s*;\s*rel="next"/);
    if (match?.[1]) return match[1];
  }
  return undefined;
}

export function parseContributors(payload: unknown): Contributor[] {
  if (!Array.isArray(payload)) throw new Error("GitHub contributors: expected an array");
  const out: Contributor[] = [];
  for (const row of payload) {
    if (!row || typeof row !== "object") continue;
    const rec = row as { login?: unknown; contributions?: unknown; type?: unknown };
    if (typeof rec.login !== "string" || typeof rec.contributions !== "number") continue;
    if (rec.type === "Bot" || rec.login.endsWith("[bot]")) continue;
    out.push({ username: rec.login, commits: rec.contributions });
  }
  out.sort((a, b) => b.commits - a.commits || a.username.localeCompare(b.username));
  return out;
}

export function renderContributorsModule(list: Contributor[]): string {
  return [
    "// GENERATED by scripts/build-contributors.ts from the GitHub contributors API.",
    "// Do not edit; run `npm run build:content` (or `npm run build`) to refresh.",
    "",
    "export interface Contributor {",
    "  username: string;",
    "  commits: number;",
    "}",
    "",
    `export const contributors: Contributor[] = ${JSON.stringify(list, null, 2)};`,
    "",
  ].join("\n");
}

function headers(token: string | undefined): Record<string, string> {
  const next: Record<string, string> = {
    Accept: "application/vnd.github+json",
    "User-Agent": "mockintosh-build",
  };
  if (token) next.Authorization = `Bearer ${token}`;
  return next;
}

export async function fetchContributorRows(
  owner: string,
  repo: string,
  token?: string,
  get: typeof fetch = fetch,
): Promise<unknown[]> {
  const rows: unknown[] = [];
  let url: string | undefined =
    `https://api.github.com/repos/${owner}/${repo}/contributors?per_page=100`;
  while (url) {
    const response = await get(url, { headers: headers(token), redirect: "follow" });
    if (!response.ok) {
      throw new Error(`GitHub contributors ${response.status} ${response.statusText}`);
    }
    const page: unknown = await response.json();
    if (!Array.isArray(page)) throw new Error("GitHub contributors: expected an array");
    rows.push(...page);
    url = parseLinkNext(response.headers.get("link"));
  }
  return rows;
}

export async function buildContributors(
  env: NodeJS.ProcessEnv = process.env,
  get: typeof fetch = fetch,
): Promise<string> {
  const { owner, repo } = resolveRepo(env);
  const rows = await fetchContributorRows(owner, repo, env.GITHUB_TOKEN, get);
  const list = parseContributors(rows);
  if (list.length === 0) throw new Error("GitHub contributors: no human contributors");
  return renderContributorsModule(list);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  try {
    const source = await buildContributors();
    fs.writeFileSync(OUTPUT_PATH, source);
    console.log(`✓ ${path.relative(ROOT, OUTPUT_PATH)}`);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (fs.existsSync(OUTPUT_PATH)) {
      console.warn(`⚠ ${message}; keeping ${path.relative(ROOT, OUTPUT_PATH)}`);
    } else {
      console.error(message);
      process.exitCode = 1;
    }
  }
}
